# Generated by Django 2.1.2 on 2018-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('surname', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('sex', models.CharField(choices=[('MALE', 'Чоловіча'), ('FEMALE', 'Жіноча')], max_length=15, verbose_name='Стать')),
                ('sign_regular_customer', models.BooleanField(verbose_name='Постійний клієнт')),
            ],
            options={
                'verbose_name': 'клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
    ]
