# Generated by Django 2.1.2 on 2018-10-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresses_app', '0002_auto_20181029_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdo',
            name='drying',
        ),
        migrations.RemoveField(
            model_name='hairdo',
            name='fixing',
        ),
        migrations.RemoveField(
            model_name='hairdo',
            name='washing',
        ),
    ]
