# Generated by Django 2.1.2 on 2018-10-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresses_app', '0003_auto_20181029_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва послуги')),
                ('price', models.FloatField(verbose_name='Вартість')),
            ],
        ),
    ]
