# Generated by Django 2.1.2 on 2018-10-29 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hairdresses_app', '0004_additionalservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата та час')),
            ],
        ),
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'verbose_name': 'додаткова послуга', 'verbose_name_plural': 'Додаткові послуги'},
        ),
        migrations.AddField(
            model_name='bill',
            name='additional_services',
            field=models.ManyToManyField(to='hairdresses_app.AdditionalService', verbose_name='Додаткова послуга'),
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairdresses_app.Client', verbose_name='Клієнт'),
        ),
        migrations.AddField(
            model_name='bill',
            name='hairdo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairdresses_app.Hairdo', verbose_name='Зачіска'),
        ),
    ]
